development:
      host: localhost
      adapter: mysql2
      database: heroku_dev
      port: 3306
      username: root
      password: tomal

test: &test
      host: localhost
      adapter: mysql2
      database: heroku_test
      port: 3306
      username: root
      password: tomal

production:
      host: localhost
      adapter: mysql2
      database: heroku_pro
      port: 3306
      username: root
      password: tomal
cucumber:
  <<: *test
